name: Build && Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : Update And Upgrade
      run  : sudo apt update && sudo apt upgrade
    - name : Install Eigen3
      run : sudo apt install libeigen3-dev
    - name : Install Opencv4
      run : sudo apt install libopencv-dev
    - name : Install Boost 
      run : sudo apt-get install libboost-all-dev
    - name : Install CMake 
      run : sudo apt install cmake
    - uses: actions/checkout@v3
      with:
        path : 'viso_imu'
    - name: Pre - Build
      run: cd $GITHUB_WORKSPACE/viso_imu/ && rm -rf build && mkdir build && cd build && cmake ..
    - name: Make
      run: cd $GITHUB_WORKSPACE/viso_imu/build/ &&  make 
    - name : Tests 
      run : echo "Run some tests here ..."
      
